### ISSUE TITLE
consider adding option to render width of hyper plan links relative to cardinality 

### ISSUE THREAD

**Issue by rickcole** [tableau/query-graphs#24]
It would be nice to optionally visualize the amount of estimated data flow via edge thickness.
Using stroke-width, one can assign the width of the links, based on the Hyper cardinalities. Here's a snippet of one possible approach:

```
    .attr('stroke-width', $.proxy(function(d) {
      let width = 0;
      if (d.count === 0) {
        width = 1;
      } else {
        width = Math.min(5, Math.max(2, Math.log10(d.count)));
      }
      return width;
    }, this))
```

**Comment by vogelsgesang** [comment]
addressed in #101
