### ISSUE TITLE
Redesign tooltip; make it possible to display multiple tooltips at the same time

### ISSUE THREAD

**Issue by vogelsgesang** [tableau/query-graphs#56]
Right now, it is only possible to display detailed information about 1 node at the same time.
This leads to usability issues in a few use cases:

* Comparing two plans: If I open 2 plans side-by-side, I can only display the detailed information for one of them at the same time. This makes it pretty hard to compare the details of the plans with each other
* Compare operators within the same plan: Again, I can only open one tooltip at the same time, so I can't efficiently compare them with each other
* Tooltip obscures parts of the tree: Sometimes (e.g. when comparing cardinality estimates and checking them against information from the tooltip), I have the issue that I can't see other relevant information rendered as part of the normal tree

I am not yet aware of a good solution.
Maybe, we should completely move away from tooltips and rather use some form of "expandable" nodes, similar to how Maya (3d modelling software) allows to expand/collapse nodes in their Node editor...
Not sure how this would influence the graph layouting, though...

**Comment by rickcole** [comment]
Perhaps mark and/or lasso a set of nodes for detailed inspection.
A short term mouse option might be to right click an open tooltip to lock it in place, or similarly a keybind.
Yet another idea, which I've seen before, to put detailed information in a side panel.

**Comment by vogelsgesang** [comment]
> Perhaps mark and/or lasso a set of nodes for detailed inspection.
> A short term mouse option might be to right click an open tooltip to lock it in place, or similarly a keybind.
Both those interactions would allow us to specify which tooltips should stay visible.
However, having multiple tooltips visible at the same time would probably mean that those tooltips overlap each other...

> Yet another idea, which I've seen before, to put detailed information in a side panel.
This is a good solution to solve the "overlaps parts of the graph below the tooltip" issue, however I am not currently sure how it would work for having details for multiple nodes displayed at the same time

**Comment by vogelsgesang** [comment]
In case we went for "expandable/collapsable nodes", we could use https://github.com/klortho/d3-flextree to layout a tree with varying node sizes

**Comment by vogelsgesang** [comment]
I took a look at a few other plan viewers and how they solve the problem

## Pev

https://dalibo.github.io/pev2/#/plan; source code: 
https://tatiyants.com/pev/#/plans/plan_1596705098890

![Screen Shot 2020-08-06 at 11 13 33](https://user-images.githubusercontent.com/6820896/89514394-172cb300-d7d6-11ea-9f8e-3e5ec0ab5357.png)

allows you to collapse/expand multiple nodes in the tree.
This approach would solve both our issues regarding a) overlap b) displaying details for multiple nodes at the same time

## Pev2

https://dalibo.github.io/pev2/#/plan; source code: https://github.com/dalibo/pev2
 
![Screen Shot 2020-08-06 at 11 21 19](https://user-images.githubusercontent.com/6820896/89515293-31b35c00-d7d7-11ea-8bc7-ee3b4eaa0b6b.png)

The expandable nodes contain additional tabs which group the displayed information
Displays explanation texts for the operators (e.g., explains what a NestedLoop join is)

## Supratimas

http://www.supratimas.com/webapp?plan.file.id=1r4tt3w

![Screen Shot 2020-08-06 at 12 00 32](https://user-images.githubusercontent.com/6820896/89519323-75f52b00-d7dc-11ea-95bc-64b86b7fa8cd.png)

Also allows you to expand/collapse multiple nodes
Displays some high-level statistics for each node by default

**Comment by vogelsgesang** [comment]
addressed in #101
