### ISSUE TITLE
Nodes are crowded when the longest node name in a plan is only somewhat less than the max length  

### ISSUE THREAD

**Issue by rickcole** [tableau/query-graphs#69]
Try the following extreme example. In practice any longest name less than 12 that includes edge labels is problematic. 

`{
  "operator": "op1",
  "input": {
    "operator": "op2",
    "input": {
      "operator": "op3"
    }
  }
}`

**Comment by vogelsgesang** [comment]
screenshot:

<img width="123" alt="Screenshot 2020-12-10 at 02 00 46" src="https://user-images.githubusercontent.com/6820896/101707454-8881b880-3a8b-11eb-9df3-46f6e4f383a6.png">

this indeed doesn't look nice...
